language: cpp

before_script:
  - echo "CC=$CXX" > make/local

addons_shortcuts:
    addons_clang38: &clang38
      apt:
        sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
        packages: [ 'clang-3.8' ]

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: "clang-3.8"
      env: CXX=clang++-3.8
      addons: *clang38
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

env:
  - TESTFOLDER=test/unit/math/memory
  - TESTFOLDER=test/unit/math/prim/scal
  - TESTFOLDER=test/unit/math/prim/arr
  - TESTFOLDER=test/unit/math/prim/mat
  - TESTFOLDER=test/unit/math/rev/scal
  - TESTFOLDER=test/unit/math/rev/arr
  - TESTFOLDER=test/unit/math/rev/mat
  - TESTFOLDER=test/unit/math/fwd/scal
  - TESTFOLDER=test/unit/math/fwd/arr
  - TESTFOLDER=test/unit/math/fwd/mat
 # - TESTFOLDER=test/unit/math/mix # times out on travis

script: ./runTests.py -j2 $TESTFOLDER

sudo: false
dist: trusty

before_install:
  - echo ${CXX}

# sudo: required
# before_install:
#   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq build-essential
#   - if [ "$CXX" = "clang++" ]; then
#       sudo apt-get install -qq clang-3.9;
#       export CXX="clang++-3.9";
#     fi
#   - if [ "$CXX" = "g++" ]; then
#       sudo apt-get install -qq g++-4.9;
#       export CXX="g++-4.9";
#     fi
