language: cpp

before_script:
  - eval "${MATRIX_EVAL}"
  - echo ${CXX}
  - ${CXX} --version
  - echo "CC=$CXX" > make/local

osx_clang: &osx_clang
  os: osx
  compiler: clang

linux_clang: &linux_clang
  os: linux
  compiler: "clang-3.8"
  addons: 
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
      packages: [ 'clang-3.8', 'libc++-dev' ]

linux_gcc: &linux_gcc
  os: linux
  compiler: "gcc-4.9"
  addons:
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.9' ]

matrix:
  fast_finish: true
  include:
    - <<: *osx_clang
      env:
        - TESTFOLDER="test/unit/math/memory test/unit/math/prim/scal test/unit/math/prim/arr"
    - <<: *osx_clang
      env:
        - TESTFOLDER=test/unit/math/prim/mat
    - <<: *osx_clang
      env:
        - TESTFOLDER="test/unit/math/rev/scal test/unit/math/rev/arr"
    - <<: *osx_clang
      env:
        - TESTFOLDER=test/unit/math/rev/mat
    - <<: *osx_clang
      env:
        - TESTFOLDER=test/unit/math/fwd
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER="test/unit/math/memory test/unit/math/prim/scal test/unit/math/prim/arr"
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER=test/unit/math/prim/mat
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER="test/unit/math/rev/scal test/unit/math/rev/arr"
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER=test/unit/math/rev/mat
    - <<: *linux_clang
      env:
        - MATRIX_EVAL="CXX=clang++-3.8"
          TESTFOLDER=test/unit/math/fwd
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER="test/unit/math/memory test/unit/math/prim/scal test/unit/math/prim/arr"
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER=test/unit/math/prim/mat
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER="test/unit/math/rev/scal test/unit/math/rev/arr"
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER=test/unit/math/rev/mat
    - <<: *linux_gcc
      env:
        - MATRIX_EVAL="CXX=g++-4.9"
          TESTFOLDER=test/unit/math/fwd

 # - TESTFOLDER=test/unit/math/mix # times out on travis

script: ./runTests.py -j2 $TESTFOLDER

sudo: false
dist: trusty
